### ISSUE TITLE
Match up headings with returnFactorMatrix

### ISSUE THREAD

**Issue by benleblanket** [tobydragon/tecmap#204]
Done When: the data returned from returnFactorMatrix has indices matched with a LearningObject list so that they could be printed together

**Comment by tobydragon** [comment]
also involves returning a continuousAssesmentMatrix

**Comment by benleblanket** [comment]
Original description parts done. Must create a continuousMatrixRecord with output data though

**Comment by benleblanket** [comment]
Confirmatory should already have factor names. needs to be put into list insterad of generic factor numbers
