### ISSUE TITLE
cells with extra text should have text stripped out to leave only score

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/tecmap#230]
Specifically, a spreadsheet can contain the following string in a cell:

45.0 (Dropped)

This is breaking things now, it shoudl be dealt with in a generic way (getting rid of any text, not just this one specific string)

done when: our csv reader accepts csvs with any kind of text plus a number in a cell, and only uses the number. If there is no number in a cell, it should not create a response for that person for that cell.

**Comment by rDeBolt** [comment]
Developed a Pullnumbers algorithm to pull only numbers (or doubles from a string). If the string does not contain a number it will return an empty string. (1 hr)

**Comment by rDeBolt** [comment]
creating tests for pull numbers to ensure it will work properly and effectivley (2 hrs)
